# Generated by Django 5.0.6 on 2024-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'basic_ai', 'advanced', 'pro'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
