# Generated by Django 5.0.6 on 2024-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('year', 'Yearly')], default='monthly', max_length=120),
        ),
    ]
