(function(g){var window=this;'use strict';var j4=function(a){a.isActive()||a.start()},rsb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},ssb=function(a,b){var c=new g.PR;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},tsb=function(a,b){var c,d,e;
return g.G(function(f){if(f.j==1)return c=a+"|"+b,g.z(f,g.sC(),2);if(f.j!=3){d=f.B;if(!d)throw g.WB("gct");return g.z(f,g.eS(d),3)}e=f.B;return f.return(e.get("captions",c))})},usb=function(a,b,c){tsb(a,b).then(function(d){d&&c(d.trackData,new g.PR(d.metadata))})},xsb=function(a){if(!vsb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(wsb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},ysb=function(){return g.pB("yt-player-caption-display-settings")},k4=function(){this.segments=[]},zsb=function(a,b){var c=g.Qb(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Fb(a.segments,c),g.Fb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.Nb(a.segments,c,0,b),g.Nb(a.segments,c+1,0,b)))},Asb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.qa=c;this.Z=d;this.G=e;this.Y=f;this.D=new k4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.uv(this.VZ,1E3,this);this.events=new g.GJ(this);g.L(this,this.N);g.L(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.zB);this.zB();this.VZ()},Bsb=function(a){return a.j&&a.j.D?a.j.D+a.player.Hc()<a.player.getCurrentTime():!1},Csb=function(a,b){if(a.policy.MC&&a.policy.Rl&&a.player.St()){var c=g.dQ(b,a.policy,{});
c.set("pot",a.player.St());c=c.De()}else c=g.dQ(b,a.policy,{}).De();var d={format:"RAW",withCredentials:!0};if(a.policy.Ha){d.method="POST";var e=b.D,f=(0,g.bZ)([120,0]);e&&g.ON(e,g.TQa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.BA(c,d,3,100).then(function(h){a:{h=h.xhr;a.Ma();if(a.B){var l=!(a.G?h.response:h.responseText)||h.status>=400,m=g.OTa(h);if(m){h=g.dQ(a.B,a.policy,{});a.B.ql(h,m);Csb(a,a.B);break a}l?a.player.ma("capfail",{status:h.status}):(a.player.Gi().hj("fcb_r"),m=a.B.jb[0].Pa,
a.Z!=null&&a.K!==m&&(l=a.B.jb[0],a.G?a.Z(h.response,(l.startTime+a.player.Hc())*1E3):a.Z(h.responseText,(l.startTime+a.player.Hc())*1E3),a.K=m))}a.B=null;a.C=null}}).Jl(function(h){a.B=null;
a.C=null;var l;a.player.ma("capfail",{status:(l=h.xhr)==null?void 0:l.status})});
a.B=b;zsb(a.D,a.B.jb[0].Pa)},l4=function(a,b){g.gV.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.oI(this.J.U())&&!this.j.isManifestless},Esb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.A0a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.rqb.get(e);q==null&&(q=Dsb[e]||Dsb[e.replace(/-/g,"_")],g.rqb.set(e,q));h=q||h}c.push(new g.PR({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Fsb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},Gsb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.A0a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Hsb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.Eqb?g.Eqb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={FF:c.FF};c.FF=d;var e=function(f){return function(){return String(a[f.FF])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.FF+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.FF,"gi"),e)}return b},m4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Re);a.params.Re&&Object.assign(r,a.params.Re);Object.assign(r,c.Re);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Re=r;var t=q.Ni===1,u=[{I:"span",S:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],w,A,C;(l=l.fb("caption_edit_on_hover")&&((w=n.getVideoData().getPlayerResponse())==null?void 0:(A=w.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",W:{tabindex:"0","aria-label":Hsb()},V:[{I:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.W.call(this,{I:"div",S:"caption-window",W:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var F=
this;this.K=[];this.Ha=!1;this.B=a;this.Na=this.La=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.Ec=c;this.ra=b;this.D=this.Ea("captions-text");this.Pb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Va=Isb(d,e,f,h);this.Dc=m;l&&(this.G=this.Ea("caption-edit"),this.T(this.G,"click",function(){F.Dc()}));
this.type=0;this.bb=this.Va*Jsb(r);this.Ab=p;a=new g.CU(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.j5,this);a.subscribe("dragmove",this.i5,this);a.subscribe("dragend",this.g5,this);this.gb=this.Ya=this.Bb=this.qb=0;a="";this.j.windowOpacity&&(a=xsb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":Ksb[this.j.textAlign]};this.Pb&&(b["border-radius"]=a?this.bb/8+"px":"");(this.C=
this.B.params.Ni===2||this.B.params.Ni===3)&&Lsb(this,this.element);g.Ls(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.tm){case 0:case 1:case 2:g.Bv(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Bv(this.element,"ytp-caption-window-bottom")}},Lsb=function(a,b){var c="vertical-rl";
a.j.OT===1&&(c="vertical-lr");g.Ns&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.Ls(b,"-o-writing-mode",c);g.Ls(b,"-webkit-writing-mode",c);g.Ls(b,"writing-mode",c);g.Ls(b,"text-orientation","upright");g.Bv(b,"ytp-vertical-caption");a.B.params.Ni===3&&(g.Ls(b,"text-orientation",""),g.Ls(b,"transform","rotate(180deg)"))},Jsb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},Msb=function(a,b){var c={},d=b.background?b.background:a.j.Re.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Re.backgroundOpacity;d=xsb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Pb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.bb/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Va*Jsb(b)+"px";d=1;e=b.color||a.j.Re.color;if(b.color||b.textOpacity!=null)e=xsb(e),d=b.textOpacity==null?a.j.Re.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.qO&&(h=e=b.qO);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.LA()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Re.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.b$&&(c.visibility="hidden");b.gZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.DR||g.VB,a.B.params.Ni===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.Vo===1||b.Vo===2||b.Vo===3||b.Vo===4||b.Vo===5)if(g.DR)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Vo){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},n4=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},Nsb=function(a){a.N=g.Bf("SPAN");
g.Ls(a.N,{display:"block"});g.Bv(a.N,"caption-visual-line");a.D.appendChild(a.N)},Osb=function(a,b){var c=g.Bf("SPAN");
g.Ls(c,{display:"inline-block","white-space":"pre-wrap"});g.Ls(c,Msb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Ls(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ls(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Psb=function(a,b,c){a.Ha=a.Ha||!!c;
var d={};Object.assign(d,a.j.Re);Object.assign(d,c||b.j);Object.assign(d,a.Ec.Re);(c=!a.N)&&Nsb(a);for(var e=a.La&&a.Na&&g.id(d,a.Na)?a.La:Osb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(Nsb(a),e=Osb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ef(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.DR||!g.Os(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Os(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Nc?g.Ls(e,m,"1em"):g.Ls(e,m,"0.5em")))}a.Na=d;a.La=e;a.K.push(b)},Isb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},Rsb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new Qsb(this);this.G=new Qsb(this);this.j=[];this.clear()},Tsb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{xw:a,
qt:b,result:0};a=Ssb[a];b=Ssb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.xe()&&c.qt===d;if(d)return{xw:a,qt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{xw:a,qt:b,result:2};return{xw:a,qt:b,result:3}},Vsb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Usb(a.D,b,c,d))},Wsb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?Vsb(a,d.gX,d.hX,b):d.type===1&&a.B&496&&Usb(a.G,d.gX,d.hX,b);a.j.length=0},o4=function(){this.type=0},p4=function(){this.state=this.qt=this.xw=0},Xsb=function(){this.timestamp=this.j=0},q4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new o4;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Xsb}},r4=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},btb=function(a,b){switch(a){case 0:return Ysb[(b&127)-32];
case 1:return Zsb[b&15];case 2:return $sb[b&31];case 3:return atb[b&31]}return 0},s4=function(a){return a.B[a.row][a.col]},t4=function(a,b,c){b>=2&&a.col>1&&(--a.col,s4(a).j=0);
var d=s4(a);d.timestamp=a.D.time+0;d.j=btb(b,c);a.col<32&&a.col++},ctb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},u4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},dtb=function(a){a.row=a.j>0?a.j:1;
a.col=1;u4(a,0,15)},etb=function(a){this.C=a;
this.G=0;this.style=new o4;this.K=new q4(this.C);this.N=new q4(this.C);this.text=new q4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},ftb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(r4(d,c),dtb(a.B),dtb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(r4(d,c),u4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},gtb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},htb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},Qsb=function(a){this.j=a;
this.G=0;this.C=new etb(this.j);this.K=new etb(this.j);this.B=new p4;this.D=this.C},Usb=function(a,b,c,d){a.B.update();
b=Tsb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.xw;c=b.qt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&t4(a,0,b),c&96&&t4(a,0,c),b!==0&&c!==0&&a.style.type===3&&r4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.xw=e,b.qt=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;ctb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));u4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:t4(b.j,0,32);break a;case 48:c===57?(d=b.j,s4(d).j=0,d.col<32&&d.col++):t4(b.j,1,c&15)}break;case 2:c&32&&t4(b.j,2,c&31);break;case 3:c&32&&t4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:gtb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,s4(d).j=0);break;case 36:d=b.j;b=s4(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:ftb(b,2,d);break;case 38:ftb(b,3,d);break;case 39:ftb(b,4,d);break;case 40:t4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);dtb(d);htb(b);break;case 43:htb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:r4(a,
d)}u4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;r4(a,d);ctb(a,b,b+1,a.j-1);u4(a,a.row,1)}break;case 46:u4(b.D,0,15);break;case 47:r4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,gtb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},itb=function(){},v4=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.LI.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},ktb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.fg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=jtb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new v4(a,b,e,c,l,d,m)}switch(m.fg){case 9:case 10:m.Vo=1;break;case 11:m.Vo=2;break;case 12:m.Vo=3;break;case 13:m.Vo=4;break;case 14:m.Vo=5}return new v4(a,b,e,c,l.textContent||"",d,m)},jtb=function(a,b,c,d,e){var f=g.LA(),h=
f?g.Bf("DIV"):g.Bf("RUBY"),l=g.Bf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Bf("DIV"):g.Bf("RP");a.textContent=b;h.appendChild(a);b=f?g.Bf("DIV"):g.Bf("RT");b.textContent=c;h.appendChild(b);c=e.fg;if(c===10||c===11||c===12||c===13||c===14)if(g.Ls(b,"text-emphasis-style","filled circle"),g.Ls(b,"text-emphasis-color","currentcolor"),g.Ls(b,"webkit-text-emphasis","filled circle"),e.fg===11||e.fg===13)g.Ls(b,"webkit-text-emphasis-position","under left"),g.Ls(b,"text-emphasis-position","under left");c=!0;if(e.fg===4||e.fg===7||e.fg===12||
e.fg===14)g.Ls(h,"ruby-position","over"),g.Ls(h,"-webkit-ruby-position","before");else if(e.fg===5||e.fg===6||e.fg===11||e.fg===13)g.Ls(h,"ruby-position","under"),g.Ls(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Bf("DIV"):g.Bf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Ls(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Ls(f,"display","none"),f=f.nextElementSibling,g.Ls(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ls(h.lastElementChild,"display","none"),d?(g.Ls(h,"padding-top","0.6em"),g.Ls(f,"top","0")):(g.Ls(h,"padding-bottom","0.6em"),g.Ls(f,"bottom","0")));return h},w4=function(){g.I.apply(this,arguments)},x4=function(a,b,c,d,e){g.LI.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},ltb=function(a){var b="_"+y4++;
return new x4(0,0x8000000000000,0,b,a)},z4=function(a){w4.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+y4++;this.K={};this.B=this.j=null;this.G=!0},A4=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},B4=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},C4=function(a,b){a=A4(a,b);
return a!==void 0?a:null},E4=function(a,b){a=a.getAttribute(b);
if(a!=null)return D4.test(a),a},mtb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=C4(b,"mh");a!=null&&(c.mB=a);a=C4(b,"ju");a!=null&&(c.textAlign=a);a=C4(b,"pd");a!=null&&(c.Ni=a);a=C4(b,"sd");a!=null&&(c.OT=a);a=E4(b,"wfc");a!=null&&(c.windowColor=a);b=A4(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},ntb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=C4(b,"ap");a!=null&&(c.tm=a);a=A4(b,"cc");a!=null&&(c.At=a);a=A4(b,"ah");a!=null&&(c.vk=a);a=A4(b,"rc");a!=null&&(c.Cs=a);b=A4(b,"av");b!=null&&(c.Xo=b);return c},otb=function(a,b,c,d){var e={};
Object.assign(e,ntb(a,b));Object.assign(e,mtb(a,b));d?g.id(e,a.C)?(d=a.D,e=a.C):d="_"+y4++:d=b.getAttribute("id")||"_"+y4++;a=A4(b,"t")+c;b=A4(b,"d")||0x8000000000000;if(e.Ni===2||e.Ni===3)c=e.Cs,e.Cs=e.At,e.At=c;return new x4(a,b,0,d,e)},F4=function(a){w4.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},G4=function(a){a=g.ze(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},ptb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Cs=a);b=b.ccColCount;b!==void 0&&(f.At=b);if(f.Ni===2||f.Ni===3)b=f.Cs,f.Cs=f.At,f.At=b;return new x4(c,d,0,e,f)},H4=function(a,b,c,d){g.gV.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.D=b.Nv},I4=function(a,b,c,d,e,f,h,l,m,n){m4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},J4=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},K4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},L4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},M4=function(a,b){w4.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new Rsb;this.j.B=1<<this.track},rtb=function(a){if(typeof a==="string")return!1;
a=new J4(a,8,0);return qtb(a)},qtb=function(a){if(!(a.byteOffset<a.j.byteLength)||L4(a)!==1380139777)return!1;
a.version=K4(a);if(a.version>1)return!1;K4(a);K4(a);K4(a);return!0},N4=function(a,b,c,d,e,f,h,l,m,n){m4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ca=[];this.qa=this.Y=this.Sa=0;this.Fa=NaN;this.Lb=0;this.Ub=null;this.Wa=new g.uv(this.cca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.CU(this.element,!0),g.L(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Bv(this.element,"ytp-caption-window-rollup");g.L(this,this.Wa);g.Ls(this.element,"overflow","hidden")},stb=function(a,b){if(!b)return"";
a.C&&a.B.params.OT!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},ttb=function(a){a.Ca=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Cs,c=0,d=0,e=a.Ca.length-1;c<b&&e>-1;){var f=a.Ca[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Fa)&&((d=a.j.At)?(e=g.Bf("SPAN"),g.Pf(e,"\u2013".repeat(d)),g.Ls(e,Msb(a,a.j.Re)),a.D.appendChild(e),a.Fa=e.offsetWidth,a.D.removeChild(e)):a.Fa=0);d=a.D;a.qa=c.call(b,a.Fa,a.Lb,(a.C?d.offsetHeight:d.offsetWidth)+1)},utb=function(a,b){ttb(a);
var c=a.Ca.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Sa){var d=c>0&&a.Sa===0,e=c<a.Sa;b||isNaN(c)||d||!e||(g.Bv(a.element,"ytp-rollup-mode"),g.vv(a.Wa));g.Ls(a.D,"transform",stb(a,c));a.Sa=c}ttb(a)},O4=function(){w4.call(this)},vtb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new v4(b,c,d,e.id,p.nodeValue,f||n>0,g.gd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);vtb(a,b,c,d,e,!0,p,q,m)}}},wtb=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},xtb=function(a,b,c,d){d=Object.assign({mB:0},d);
return new x4(a,b,c,"_"+y4++,d)},P4=function(a,b){g.I.call(this);
this.J=a;this.X=b;this.j=null;this.B=this.J.lA()},ytb=function(a){if(typeof a==="string"||rtb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.tP(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.tN(a)},Atb=function(a,b,c){if(typeof b==="string"||rtb(b))return[{trackData:b,
HT:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.vSa(d);if(a.B&&e){var f=g.mSa(e),h=g.nSa(e);e=e.dj;f&&e&&a.B.MH(e,f,h)}a=g.AP(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.tN(e),f.push({trackData:e,HT:c+h*1E3});ztb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},ztb=function(a,b,c){var d=g.tP(a,0,1836476516),e=9E4;
d&&(e=g.uP(d)||9E4);d=0;for(var f=g.AP(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.tP(a,l.dataOffset,1953653094))&&(l=g.tP(a,l.dataOffset,1952867444))&&(l=g.sSa(l)/e*1E3,h===0&&(d=l),b[h].HT=l-d+c||c*h*1E3)}},Btb=function(a,b,c,d,e){if(!rtb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new M4(e,b));return a.j.Lo(c,d)},Ctb=function(a,b,c){a.j||(a.j=new O4);
a=a.j.Lo(b,c);Math.random()<.01&&g.eE(Error("Deprecated subtitles format in web player: WebVTT"));return a},Etb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new F4(Dtb(b))),a.j.Lo(c,d)}catch(f){return g.dE(f),[]}var e=g.$1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new z4(Dtb(b),a.X)),a.j.Lo(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Dtb=function(a){var b=
{};
if(a=g.SR(a))b.lang=a,g.ymb.test(a)&&(b.Ni=1);return b},Q4=function(a){g.dV.call(this,a);
var b=this;this.J=a;this.X=this.J.U();this.videoData=this.J.getVideoData();this.Bb=this.J.ob();var c;this.gb=(c=this.J.getVideoData(1))==null?void 0:g.zS(c);this.C={Re:{}};this.G={Re:{}};this.Ha=[];this.ra={};this.Va={};this.Y=!1;this.Pb=g.dT(this.videoData);this.Ya=g.B0a(this.videoData,this.J);this.Lb=!!this.videoData.captionTracks.length;this.Ub=!!this.videoData.kf;this.Wa=this.X.controlsType==="3";this.j=this.N=this.Z=this.Sa=this.qb=null;this.bb=new P4(this.J,this.X);this.B=null;this.Ca=new g.GJ(this);
this.K=new g.W({I:"div",S:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.aw("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Tv(d));this.storage=c;var e;this.Kb=!((e=a.Le())==null||!e.DH());this.D=Ftb(this);this.Fa=!this.D&&this.Wa&&this.Kb&&this.Ya;g.L(this,this.bb);this.D?this.Na=this.La=null:(this.La=new g.jv(this.dU,void 0,this),g.L(this,this.La),this.Na=new g.uv(this.Cda,2E3,this),g.L(this,
this.Na));g.L(this,this.Ca);g.ET(this.player,this.K.element,4);g.L(this,this.K);this.D||this.Ca.T(a,"resize",this.gU);(this.Ab=g.nR(this.X)&&!g.aB()&&!this.J.isFullscreen()&&!this.D&&!this.Fa)&&this.Ca.T(a,"resize",this.lba);this.Ca.T(a,"onPlaybackAudioChange",this.zaa);this.Ca.T(a,g.MI("captions"),function(f){b.onCueRangeEnter(f)});
this.Ca.T(a,g.NI("captions"),function(f){b.onCueRangeExit(f)});
this.gb&&this.Ca.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
Gtb(this,ysb()||{});this.player.Cc("onCaptionsModuleAvailable")},Jtb=function(a){if(a.X.Kb===1||a.videoData.XH===1||g.NS(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.X.Kb===2){if(g.zR(a.X))var c=Htb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=rsb(a.player.getAudioTrack(),g.zR(a.X));var d=g.NS(a.videoData,"yt:cc");if(Itb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.NS(a.videoData,
"yt:cc")==="on"},R4=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},Itb=function(a){var b=void 0,c=g.uB(g.tB(),65);
if(g.zR(a.X)&&c!=null){if(Htb(a)!=null)return!1;b=!c}return b},Ktb=function(a){var b;
a.Pb?b=new H4(a.X,a.videoData,a.getAudioTrack(),a.player):a.Ya?b=new l4(a.videoData.j,a.player):a.Lb?b=new g.hV(a.X,a.videoData,a.getAudioTrack()):b=new g.lV(a.X,a.videoData.kf,a.videoData.videoId,g.sYa(a.videoData),a.videoData.yn,a.videoData.eventId);return b},T4=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.ZS(a.videoData)&&(b=!0);b||(b=a.Ub?!1:a.Lb?!1:!0);b=b||Ltb(a);b=g.eV(a.j.B,b);var c=null;if(g.zR(a.X)){var d=a.J.isInline()?void 0:g.pB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.NS(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.SR(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.SR(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.v(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.NS(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.SR(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||S4(a));d&&c&&g.SR(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=ssb(d,c));return d}return null},S4=function(a){return a.N&&a.N.j},U4=function(a){var b=S4(a);
return!!b&&a.B===b},Mtb=function(a){var b=rsb(a.player.getAudioTrack(),g.zR(a.X)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=T4(a,a.Y):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&R4(a)?c=S4(a):Itb(a)||a.Y||Jtb(a)?c=T4(a,a.Y):R4(a)&&(c=S4(a));if(a.D||a.Fa){var d=g.eV(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Bf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.QR(f));h.setAttribute("srclang",g.SR(f));h.setAttribute("id",f.toString());a.Fa||h.setAttribute("src",a.j.Xw(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Le();c.WD(b);c=
c.Jb();a.Kb&&a.Ca.T(c.textTracks,"change",a.Ica)}else!a.B&&c&&V4(a,c),a.player.Cc("onCaptionsTrackListChanged"),a.player.Xm("onApiChange")},Ntb=function(a,b){var c=a.J.Le().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},V4=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.Y=c,a.Y&&(g.zR(a.X)?W4(a,!!b):X4(a,!!b)));a.B=b;R4(a)&&(a.B=S4(a));var d;Otb(a,(d=a.B)!=null?d:void 0);a.load()},Qtb=function(a,b){if(b instanceof x4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=Ptb(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},Ptb=function(a,b){var c=Rtb(a);
if(!c)return null;var d=a.B?g.SR(a.B):null;d&&g.ymb.test(d)&&(b.params.Ni=1);var e=a.Bb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.X.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.mB!=null?b.params.mB:b.j.length>1?1:0){case 1:return new I4(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.XM.bind(a),a.J);case 2:return new N4(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.XM.bind(a),a.J);default:return new m4(b,a.C,a.G,c.width,c.height,e,
d,a.X.experiments,a.XM.bind(a),a.J)}},Gtb=function(a,b,c){c=c===void 0?!1:c;
var d=Y4.Re;a.C={};Object.assign(a.C,Y4);a.C.Re={};Object.assign(a.C.Re,d);a.G={Re:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;D4.test(f);e.Re.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;D4.test(f);e.Re.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||Y4.windowColor;D4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Re.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Re.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Re;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Re.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=Y4.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Re.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Re.fontFamily=f;a.loaded&&a.gU();c&&g.oB("yt-player-caption-display-settings",b,2592E3)},Ttb=function(a,b,c){b&&!a.Z?(b=ltb({Ni:0,
lang:"en"}),a.Z=[b,new v4(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.mf(a.Z)):!b&&a.Z&&(Stb(a,a.Z),a.Z=null)},Stb=function(a,b){a.player.To(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.Gb(a.Ha,c.value);j4(a.La)},Otb=function(a,b){a.X.L("html5_modify_caption_vss_logging")&&(a.videoData.AD=b)},Rtb=function(a){var b=a.Bb.getVideoContentRect(!0).height,c=a.Bb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},X4=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},W4=function(a,b){a.J.isInline()||g.oB("yt-player-sticky-caption",b,2592E3)},Htb=function(a){if(!a.J.isInline())return g.pB("yt-player-sticky-caption")},Ftb=function(a){var b,c=!((b=a.J.Le())==null||!b.CH());
return a.Wa&&c&&!a.Ya},Ltb=function(a){return a.X.L("web_deprecate_always_includes_asr_setting")&&g.zR(a.X)?!0:!!g.uB(g.tB(),66)};
g.UX.prototype.QE=g.ca(44,function(a){var b=2;this.K.has(a)?b=0:g.$6a(this,a)&&(b=1);return b});
g.v_.prototype.QE=g.ca(43,function(a){return this.Zc.QE(a)});
g.UX.prototype.MH=g.ca(42,function(a,b,c){this.La.set(a,{Ht:b,rz:c})});
g.v_.prototype.MH=g.ca(41,function(a,b,c){this.Zc.MH(a,b,c)});
g.gV.prototype.xS=g.ca(40,function(){return!1});
g.gV.prototype.Du=g.ca(39,function(){});
g.hV.prototype.Du=g.ca(38,function(a,b,c){var d=this;this.Ma();b=this.Xw(a,b);this.Qs();this.j=g.yA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.lV.prototype.Du=g.ca(37,function(a,b,c){var d=this;this.Ma();b=this.Xw(a,b);this.Qs();this.j=g.yA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.KU.prototype.Gz=g.ca(36,function(){for(var a=g.pf(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Mf(a[b])});
g.yX.prototype.Gz=g.ca(35,function(){this.mediaElement.Gz()});
g.KU.prototype.DH=g.ca(34,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.yX.prototype.DH=g.ca(33,function(){return this.mediaElement.DH()});
g.KU.prototype.CH=g.ca(32,function(){return!!this.j.textTracks});
g.yX.prototype.CH=g.ca(31,function(){return this.mediaElement.CH()});
g.KU.prototype.WD=g.ca(30,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.yX.prototype.WD=g.ca(29,function(a){this.mediaElement.WD(a)});
g.q_.prototype.eF=g.ca(19,function(){return this.K});
g.D0.prototype.eF=g.ca(18,function(){var a;return((a=g.rT(this))==null?void 0:a.lA())||null});
g.xT.prototype.lA=g.ca(17,function(){return this.app.eF()});
g.s0.prototype.lA=g.ca(16,function(){var a;return((a=this.ya)==null?void 0:a.eF())||null});
g.iP.prototype.RJ=g.ca(2,function(a){return(a=this.On(a))?a.j:0});
g.GTa.prototype.RJ=g.ca(1,function(){return 0});
var wsb=/#(.)(.)(.)/,vsb=/^#(?:[0-9a-f]{3}){1,2}$/i,Dsb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
k4.prototype.contains=function(a){a=g.Qb(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
k4.prototype.length=function(){return this.segments.length/2};
g.x(Asb,g.I);g.k=Asb.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.zB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Hc();var b=this.j;this.j=g.zb(this.qa.Ir(a).jb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new k4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.VZ=function(){this.Ma();var a;if(a=this.j!=null)a=this.j,a=a.j.Ys(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.tD(a);var b=a.jb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.lA()){var d=b.j.info.id,e=b.Pa,f=a.jb[0].C;if(this.policy.Ha){if(c=c.UJ(f,e,d,3))a.D=c}else if(d=c.eA(f,e,d,3))if(c=c.QE(e),c===0)d&&(a.j=new g.bP(d));else if(c===2){this.N.start();Bsb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Zn(b.Pa)?(this.D.contains(a.jb[0].Pa)||Csb(this,a),this.j=g.zb(a.jb)):Bsb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.x(l4,g.gV);g.k=l4.prototype;g.k.Du=function(a,b,c){var d=this;this.Qs();b=Fsb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?Gsb(this,b,"386"):Gsb(this,b));if(b){var e=(b.index.RJ(b.index.Qn())-b.index.getStartTime(b.index.Qn()))*1E3,f=new g.x0a(this.X),h=function(){d.C&&d.C.reset();d.G=!0};
this.X.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Asb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.RJ(b.info),h)}};
g.k.xS=function(){var a=this.G;this.G=!1;return a};
g.k.YA=function(a){var b=this.K?[new g.PR({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.PR({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?Esb(this,"386"):Esb(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.fV(this.B,c.value);a()};
g.k.Qs=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Xw=function(){return""};
var D4=/^#(?:[0-9a-f]{3}){1,2}$/i;var Ksb=["left","right","center","justify"];g.x(m4,g.W);g.k=m4.prototype;g.k.j5=function(a,b){this.Ya=a;this.gb=b;var c=g.Vs(this.element,this.element.parentElement);this.qb=a-c.x;this.Bb=b-c.y};
g.k.i5=function(a,b){if(a!==this.Ya||b!==this.gb){g.Av(this.element,"ytp-dragging")||g.Bv(this.element,"ytp-dragging");var c=g.Xs(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.Bb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ze(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.ze(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.ze(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.ze(c,0,1)*100;this.B.params.tm=b;this.B.params.Xo=c;this.B.params.vk=
a;this.B.params.isDefault=!1;this.j.tm=b;this.j.Xo=c;this.j.vk=a;this.j.isDefault=!1;this.ra.tm=b;this.ra.Xo=c;this.ra.vk=a;this.ra.isDefault=!1;this.z1()}};
g.k.g5=function(){g.Dv(this.element,"ytp-dragging")};
g.k.z1=function(){this.oC(this.K)};
g.k.getType=function(){return this.type};
g.k.oC=function(a){var b=this.Ab?0:Math.min(this.lY(),this.maxWidth),c=this.kY(),d=this.Ab;if(d){var e=getComputedStyle(this.D.parentNode);e=n4(e.borderLeftWidth)+n4(e.borderRightWidth)+n4(e.paddingLeft)+n4(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Ni===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Ls(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.VN(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.vk*.96+2;h=this.j.tm;switch(h){case 0:case 3:case 6:(d=this.j.Re.fontSizeIncrement)&&d>0&&this.j.Ni!==2&&this.j.Ni!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.Xo*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Ls(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.VN=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ha||this.K.length>b)b=0,this.Ha=!1,this.K=[],this.N=this.Na=this.La=null,g.Gf(this.D);for(;b<a.length;b++)Psb(this,a[b])};
g.k.lY=function(){return 0};
g.k.kY=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};Rsb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Rsb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Ssb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];o4.prototype.set=function(a){this.type=a};
o4.prototype.get=function(){return this.type};
p4.prototype.clear=function(){this.state=0};
p4.prototype.update=function(){this.state=this.state===2?1:0};
p4.prototype.xe=function(){return this.state!==0};
p4.prototype.matches=function(a,b){return this.xe()&&a===this.xw&&b===this.qt};
Xsb.prototype.reset=function(){this.timestamp=this.j=0};
q4.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
q4.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
q4.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Ysb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Zsb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],$sb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],atb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];etb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Qsb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};itb.prototype.D=function(){};g.x(v4,g.LI);v4.prototype.toString=function(){return g.LI.prototype.toString.call(this)};g.x(w4,g.I);w4.prototype.Lo=function(){return[]};
w4.prototype.reset=function(){};g.x(x4,g.LI);x4.prototype.toString=function(){return g.LI.prototype.toString.call(this)};
var y4=0;g.x(z4,w4);z4.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
z4.prototype.Lo=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=B4(a,"b");
l!=null&&(h.bold=l);l=B4(a,"i");l!=null&&(h.italic=l);l=B4(a,"u");l!=null&&(h.underline=l);l=C4(a,"et");l!=null&&(h.charEdgeStyle=l);l=C4(a,"of");l!=null&&(h.offset=l);l=E4(a,"bc");l!=null&&(h.background=l);l=E4(a,"ec");l!=null&&(h.qO=l);l=E4(a,"fc");l!=null&&(h.color=l);l=C4(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=A4(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=A4(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=A4(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=C4(a,"rb");l!=null&&l!==10&&
l!==0&&(h.fg=l>10?l-1:l);a=C4(a,"hg");a!=null&&(h.gZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=mtb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=ntb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=otb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!B4(m,"a");l=(A4(m,"t")||0)+l;var n=A4(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var w=void 0;t.nodeType===1&&(w=t);if(w&&w.tagName==="s"){if((t=(t=w.getAttribute("p"))?this.pens[t]:null)&&t.fg&&(t.fg===1?(t=r.slice(m,
m+4),t.length===4&&(u=ktb(l,n,f,h,p,t,this.pens),m+=3)):u=ktb(l,n,f,h,p,[w],this.pens)),!u){var A=w;u=l;w=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",M=A.getAttribute("p");M=M?this.pens[M]:null;A=A4(A,"t")||0;u=new v4(u+A,w-A,F,t,H,C,M)}}else u=new v4(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=otb(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Utb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(F4,w4);F4.prototype.reset=function(){this.B.clear()};
F4.prototype.Lo=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.qO=G4(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=G4(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=G4(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.fg=h>10?h-1:h,f.Vo=Utb.get(f.fg));e.hgHorizGroup&&(f.gZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.mB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Ni=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.OT=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=G4(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.vk=e.ahHorPos),e.apPoint!==void 0&&(f.tm=e.apPoint),e.avVerPos!==void 0&&(f.Xo=e.avVerPos),e.ccCols!==void 0&&(f.At=e.ccCols),e.rcRows!==void 0&&(f.Cs=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=ptb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+y4++,d=ptb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var w=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.mB!=null?l.params.mB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],F;if(F=A&&A.fg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var M=F[H+1].pPenId;(M=this.j.get(M))&&M.fg&&M.fg===2?(M=F[H+2].pPenId,M=this.j.get(M),!M||!M.fg||
M.fg<3?F=!1:(M=F[H+3].pPenId,F=(M=this.j.get(M))&&M.fg&&M.fg===2?!0:!1)):F=!1}}if(F)w=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=jtb(u,w,F,t,H),t=new v4(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;C=A;F=r;H=e;M=f;var Q=w,da=p,na=n,qa=[],ha=g.$1("<html>"+u+"</html>");if(!ha.getElementsByTagName("parsererror").length&&((N=ha.firstChild)==null?0:N.childNodes.length))for(N=g.v(ha.firstChild.childNodes),ha=N.next();!ha.done;ha=N.next()){ha=ha.value;var ta=void 0,
P=void 0,ua=(P=(ta=ha.textContent)==null?void 0:ta.replace(/\n/g,""))!=null?P:"";if(ha.nodeType!==3||ua&&ua.match(/^ *$/)==null){ta={};Object.assign(ta,C||F);P=void 0;switch((P=ha)==null?void 0:P.tagName){case "b":ta.bold=!0;break;case "i":ta.italic=!0;break;case "u":ta.underline=!0}qa.push(new v4(H+Q,M-Q,da,l.id,ua,na,ta))}}C=qa}C.length||(C=[new v4(e+w,f-w,p,l.id,u,n,A||r)])}if(C.length)for(n=g.v(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=
!0}}}b=a}else b=[];return b};g.x(H4,g.gV);H4.prototype.Du=function(a,b,c){usb(this.videoData.videoId,a.vssId,c)};
H4.prototype.YA=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.fV(this.B,c.value);a()};g.x(I4,m4);I4.prototype.VN=function(a){var b=this.B.j;m4.prototype.VN.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Vtb);var e=c.j;var f=d}Psb(this,c,d)}};
var Vtb={b$:!0};g.x(J4,itb);J4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+y4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new x4(c,d-c,5,f,{textAlign:0,tm:0,vk:b*2.5,Xo:a*5.33});e=new v4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.x(M4,w4);M4.prototype.Lo=function(a){a=new J4(a,a.byteLength,this.B);if(qtb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=L4(a)*(1E3/45):a.version===1&&(a.C=L4(a)*4294967296+L4(a)),a.G=K4(a);a.G>0;a.G--){var b=K4(a),c=K4(a),d=K4(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,gX:c,hX:d,order:b.j.length}))}Wsb(this.j,a);return a.B}return[]};
M4.prototype.reset=function(){this.j.clear()};g.x(N4,m4);g.k=N4.prototype;g.k.z1=function(){g.wv(this.Wa)};
g.k.cca=function(){g.Dv(this.element,"ytp-rollup-mode");this.oC(this.Ub,!0)};
g.k.kY=function(){return this.C?this.qa:this.Y};
g.k.lY=function(){return this.C?this.Y:this.qa};
g.k.oC=function(a,b){this.Ub=a;if(this.B.params.Cs){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Lb=this.qa;this.Y=this.qa=0;m4.prototype.oC.call(this,a);utb(this,b)}m4.prototype.oC.call(this,a)};g.x(O4,w4);
O4.prototype.Lo=function(a,b){var c=[];a=a.split(Wtb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Xtb.test(e)){var h=Ytb.exec(e);if(h&&h.length>=4){var l=wtb(h[1]),m=wtb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.v(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var w=u[1];switch(u[0]){case "line":u=w.split(",");u[0].endsWith("%")&&(p=u[0],h.Xo=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
w.split(",");r=u[0];h.vk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(w){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.vk=0;break;case 1:h.vk=100;break;case 2:h.vk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.tm=q}e=e.substring(Ytb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=xtb(l,m,5,t),m=new v4(l,m,5,f.id,h,!1,g.gd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Ztb),q.length===1?(h=5,t=xtb(l,m,h,t)):(p=h=6,t=Object.assign({At:32},t),t=new x4(l,m,p,"_"+y4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.$1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(w=u.createElement("span"),w.appendChild(u.createTextNode(n))):w=u.firstChild,vtb(this,p,m-(p-l),h,t,r>0,w,e,c)):p=wtb(n)+f}Ytb.lastIndex=0}}return c};
var Xtb=/^NOTE/,Wtb=/(?:\r\n|\r|\n){2,}/,Ytb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ztb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.zX.nK(O4,{Lo:"wvppt"});g.x(P4,g.I);
P4.prototype.Lo=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){a:{var e=d,f=Atb(this,a,c),h=[];try{for(var l=g.v(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.HT;h=typeof p!=="string"?h.concat(Btb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(Ctb(this,p,q)):h.concat(Etb(this,b,p,q))}var r=h;break a}catch(t){g.dE(t);this.clear();r=[];break a}r=void 0}if(r.length!==0)return r}a=ytb(a);if(!a)return[];try{return typeof a!=="string"?Btb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?
Ctb(this,a,c):Etb(this,b,a,c)}catch(t){return g.dE(t),this.clear(),[]}};
P4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
P4.prototype.reset=function(){this.j&&this.j.reset()};
P4.prototype.xa=function(){g.I.prototype.xa.call(this);this.clear()};var Y4={windowColor:"#080808",windowOpacity:0,textAlign:2,tm:7,vk:50,Xo:100,isDefault:!0,Re:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(Q4,g.dV);g.k=Q4.prototype;g.k.xa=function(){if(this.D||this.Fa){var a=this.J.Le();a&&!a.Ma()&&a.Gz()}else Ttb(this,!1);g.dV.prototype.xa.call(this)};
g.k.xT=function(){return this.X.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Ya};
g.k.bv=function(){if(this.Wa)return this.D||this.Fa;var a=this.getAudioTrack();if(this.xT()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=rsb(a,g.zR(this.X));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?R4(this):Itb(this)||R4(this)?!0:Jtb(this)};
g.k.load=function(){var a=this;g.dV.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.bb.clear(),this.D?Ntb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Du(this.B,"json3",function(b,c,d,e){if(b){var f;Otb(a,(f=a.B)!=null?f:void 0);a.j.xS()&&(a.Ha=[],a.J.tf("captions"),j4(a.La),a.bb.reset());if(a.videoData.Uf){var h;d=((h=d)!=null?h:0)+a.videoData.Uf}b=a.bb.Lo(b,c,d,e);if(a.gb)for(c=g.v(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Cl=a.videoData.Uf;c=!a.X.L("html5_keep_caption_data_after_seek")&&a.Ya;a.player.mf(b,void 0,c);!a.Y||a.Fa||U4(a)||!a.X.jm||g.qI(a.X)||g.pR(a.X)||g.HF(a.X)||a.X.La==="shortspage"||a.player.isInline()||(g.xv(a.Na),b=ltb({tm:0,vk:5,Xo:5,Cs:2,textAlign:0,Ni:0,lang:"en"}),a.Sa=[b],c=["Click "," for settings"],a.qb||(e=new g.BE(g.Tya()),g.L(a,e),a.qb=e.element),e=b.end-b.start,(f=g.QR(a.B))&&a.Sa.push(new v4(b.start,e,0,b.id,f)),a.Sa.push(new v4(b.start,e,0,b.id,c[0]),new v4(b.start,e,0,b.id,a.qb,!0),
new v4(b.start,e,0,b.id,c[1],!0)),a.player.mf(a.Sa),g.vv(a.Na));!a.Y||a.Fa||U4(a)||(g.zR(a.X)?W4(a,!0):X4(a,!0),a.N&&(a.N.D=a.B),a.player.gp());a.Y=!1}}),this.D||this.Fa||U4(this)||this.player.Cc("captionschanged",g.RR(this.B))):(this.j=Ktb(this),g.L(this,this.j),this.j.YA(function(){Mtb(a)}))};
g.k.unload=function(){this.D&&this.B?Ntb(this,!1):(this.Na&&g.xv(this.Na),this.player.tf("captions"),this.Ha=[],this.j&&this.j.Qs(),this.bb.clear(),this.Z&&this.player.mf(this.Z),this.gU());g.dV.prototype.unload.call(this);this.player.gp();this.player.Cc("captionschanged",{})};
g.k.create=function(){this.bv()&&this.load();var a;a:{var b,c,d;if(this.X.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.Ica=function(){for(var a=this.J.Le().Jb().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.eV(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&V4(this,b,!0)};
g.k.efa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ha.push(a);j4(this.La)};
g.k.onCueRangeExit=function(a){g.Gb(this.Ha,a);this.j instanceof l4&&this.j.K&&this.player.To([a]);j4(this.La)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.Cda=function(){Stb(this,this.Sa);this.Sa=null};
g.k.dU=function(){var a=this;if(!this.Ab||!this.D){this.La.stop();g.eba(this.Va);this.Ha.sort(g.rDa);var b=this.Ha;if(this.Z){var c=g.Pt(b,function(f){return this.Z.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())Qtb(this,c.value);b=g.v(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={BA:void 0,Fp:void 0},d=b.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;c.BA=d;c.Fp=e;this.Va[c.BA]?(c.Fp.element.parentNode||(c.Fp instanceof N4||c.Fp instanceof I4||g.Xc(this.ra,function(f){return function(h,l){l!==f.BA&&h.B.params.tm===f.Fp.B.params.tm&&h.B.params.vk===f.Fp.B.params.vk&&h.B.params.Xo===f.Fp.B.params.Xo&&(h.dispose(),delete a.ra[l]);
return l===f.BA}}(c),this),this.K.element.appendChild(c.Fp.element)),c.Fp.oC(this.Va[c.BA])):(c.Fp.dispose(),delete this.ra[c.BA])}}};
g.k.Ida=function(){Gtb(this,{},!0);this.player.Cc("captionssettingschanged")};
g.k.m9=function(){var a=Y4.Re;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:Y4.windowColor,windowOpacity:Y4.windowOpacity};var b=ysb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.r3=function(a,b){var c={};Object.assign(c,ysb());Object.assign(c,a);Gtb(this,c,b);this.player.Cc("captionssettingschanged")};
g.k.gU=function(){!this.D&&this.loaded&&(g.Tc(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.dU())};
g.k.Uh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ze(b,-2,4);this.r3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&V4(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.X.N&&(g.zR(this.X)?W4(this,!!b):X4(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.db(b))break;if(g.gd(b)){V4(this,null,!0);break}a=g.eV(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||"")||g.QR(e)!==b.displayName)||(c=b.translationLanguage?ssb(e,b.translationLanguage):e)}this.DM(b.position);!c||c===this.B&&this.loaded||(b=g.sQa(),a=g.SR(c),b.length&&a===b[b.length-1]||(b.push(a),g.oB("yt-player-caption-language-preferences",b)),g.zR(this.X)&&!this.J.isInline()&&g.oB("yt-player-caption-sticky-language",a,2592E3),V4(this,c,!0))}else return this.loaded&&this.B&&!U4(this)?g.RR(this.B):{};return"";case "tracklist":return this.j?g.cs(g.eV(this.j.B,!(!b||
!b.includeAsr)),function(f){return g.RR(f)}):[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||Ttb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Ttb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.sQa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.N&&a.push("stickyLoading");return a};
g.k.Jr=function(){var a=this.B;if(this.X.L("html5_cue_ranges_based_caption_vss")&&!this.J.cK("captions"))return{};if(this.X.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.AD)!=null?b:null)?{cc:g.mWa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.SR(a)),{cc:b}):{}};
g.k.Qea=function(){this.isSubtitlesOn()?(g.zR(this.X)?W4(this,!1):X4(this,!1),Otb(this),this.unload(),R4(this,!0)&&V4(this,S4(this),!1)):this.N2()};
g.k.N2=function(){this.isSubtitlesOn()||V4(this,U4(this)||!this.B?T4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!U4(this)};
g.k.zaa=function(){var a=U4(this);R4(this,a)?V4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.xT()&&(this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.bv()&&(a?V4(this,T4(this),!1):this.load()))};
g.k.DM=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=Rtb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Cc("captionschanged",{})),this.bv()&&this.load())};
g.k.getAudioTrack=function(){return this.gb&&this.player.getPresentingPlayerType()===2?this.videoData.Qk:this.player.getAudioTrack()};
g.k.lba=function(){var a=this.J.Le();a&&!a.Ma()&&a.Gz();this.J.isFullscreen()?(this.D=this.Wa=!0,this.loaded&&Mtb(this)):(this.Wa=this.X.controlsType==="3",this.D=Ftb(this));V4(this,this.B)};
g.k.XM=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.ib("innertubeCommand",d)};
g.zX.nK(Q4,{dU:"smucd"});g.cV("captions",Q4);})(_yt_player);
