(function(g){var window=this;'use strict';var $wb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");c===-1&&(c=a.length);var d=a[0]==="-"?"-":"";d&&(a=a.substring(1));return d+(0,g.hlb)("0",Math.max(0,b-c))+a},axb=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},bxb=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},dxb=function(a){typeof a==="number"?(this.date=cxb(a,0,1),x6(this,1)):g.db(a)?(this.date=cxb(a.getFullYear(),a.getMonth(),a.getDate()),x6(this,a.getDate())):(this.date=new Date(g.kb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),x6(this,a))},cxb=function(a,b,c){b=new Date(a,b,c);
a>=0&&a<100&&b.setFullYear(b.getFullYear()-1900);return b},x6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},y6=function(a,b){g.IT.call(this,a,{I:"div",
S:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.j=b;this.C=[];this.menuPopupRenderer=void 0;this.items=this.Ea("ytp-reminder-menu-items");this.hide()},exb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},z6=function(a){g.W.call(this,{I:"div",
V:[{I:"button",Ka:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",va:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",va:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.G=this.Ea("ytp-offline-slate-button"))&&this.T(this.G,"click",this.K);this.hide()},gxb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.V(c,fxb)?a.upcomingEventReminderButtonRenderer=g.V(c,fxb):c&&g.V(c,fxb)||(a.upcomingEventReminderButtonRenderer=null);A6(a)},A6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.IE(b.toggledText):"";a.update({text:c,icon:hxb(b.toggledIcon)})}else c=b.defaultText?g.IE(b.defaultText):"",a.update({text:c,icon:hxb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=ixb(a))?(c=b.text?g.IE(b.text):"",a.update({text:c,icon:hxb(b.icon)}),a.show()):a.hide():a.hide()},kxb=function(a,b,c){a.D||(a.D=new g.bD(a.J.U().Mk));
var d={context:g.rua(a.D.config_||g.CC())};g.aE()&&(d.context.clientScreenNonce=g.aE());d.params=c;g.cD(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){jxb(a)},
onTimeout:function(){jxb(a)}})},jxb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,A6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,A6(a))},hxb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return axb();case "NOTIFICATIONS_NONE":return bxb();case "NOTIFICATIONS_ACTIVE":return g.Mya();default:return null}},ixb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.v(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.V(c.value,lxb))&&c.state===b&&c.button&&g.V(c.button,g.YL))return g.V(c.button,g.YL);return null},mxb=function(a){g.W.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},va:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",va:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",Ka:["ytp-offline-slate-close-button","ytp-button"],V:[g.LE()]},{I:"button",Ka:["ytp-offline-slate-open-button","ytp-button"],V:[g.KE()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ea("ytp-offline-slate-background");
this.C=this.Ea("ytp-offline-slate-bar");this.G=new g.uv(function(){g.Bv(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.uv(function(){g.Bv(b.element,"ytp-offline-slate-collapsed")},15E3);
g.L(this,this.D);g.L(this,this.G);this.countdownTimer=new g.uv(this.l3,1E3,this);this.T(a,"presentingplayerstatechange",this.q3);this.T(a,"livestatedata",this.Ta);a=this.Ea("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Bv(b.element,"ytp-offline-slate-collapsed")});
a=this.Ea("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Dv(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ta(a);a=this.api.getPresentingPlayerType()===8&&!this.getVideoData().jm;var c=this.api.getPresentingPlayerType()===8;g.Fv(this.element,"ytp-offline-slate-premiere-trailer",a);g.Fv(this.element,"ytp-offline-slate-hide-background",c)},nxb=function(a,b,c){if(b){var d=b.subtitleText!=null?g.IE(b.subtitleText):"";
c=c?c:b.mainText!=null?g.IE(b.mainText):"";var e,f,h,l;b=(l=(e=b.mainText)==null?void 0:(f=e.accessibility)==null?void 0:(h=f.accessibilityData)==null?void 0:h.label)!=null?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Fv(a.element,"ytp-offline-slate-single-text-line",!d);g.Fv(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},B6=function(a,b){var c=(0,g.$B)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},txb=function(a){g.dV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.uv(function(){oxb(b)},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.Wm(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qa=new g.bD(void 0);this.attestationResponse=Promise.resolve(void 0);this.Y=Promise.resolve(void 0);this.utcOffsetMinutes=-(new dxb).getTimezoneOffset();this.C=new g.GJ(this);g.L(this,this.B);g.L(this,this.C);pxb(this);qxb(this);this.C.T(a,"heartbeatparams",this.jG);this.C.T(a,"presentingplayerstatechange",this.u5);this.C.T(a,"videoplayerreset",this.v5);this.C.T(a,g.MI("heartbeat"),
this.onCueRangeEnter);this.D&&this.j&&rxb(this,void 0,this.j);var c=new g.LI(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.LI(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.mf([c,d]);sxb(this)},sxb=function(a){var b=a.getVideoData();
!b.L("use_rta_only_for_player")&&b.Tl&&(b=b.botguardData)&&g.gQa(b,a.player.U())},uxb=function(a){var b,c;
return g.G(function(d){if(d.j==1)return g.z(d,g.rBa(),2);if(!d.B)return a.sequenceNumber>=3?d.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):d.return(void 0);b=a.getVideoData();c={};return d.return(g.qBa((c.cpn=b.clientPlaybackNonce,c.encryptedVideoId=b.videoId||"",c),1500))})},pxb=function(a){var b=a.getVideoData();
if(b.Tl)if(b.L("use_rta_for_player_hb"))a.attestationResponse=uxb(a);else if(b=new g.eQa(b),g.wO.isInitialized()||a.sequenceNumber>=3){var c=Promise,d=c.resolve,e=null;if(b.videoData.jr){var f=g.fQa(b);if(f){e={};var h={};f=f.split("&");f=g.v(f);for(var l=f.next();!l.done;l=f.next())l=l.value.split("="),l.length===2&&(h[l[0]]=l[1]);h.r1a&&(e.webResponse=h.r1a);h.r1c&&(e.error=vxb[Number(h.r1c)]);e.challenge=b.videoData.jr}}a.attestationResponse=d.call(c,e||void 0)}},wxb=function(a){var b=a.getVideoData();
if(!g.LS(a.getVideoData())||b.L3)return!1;if(b.useInnertubeDrmService()&&b.K){a=b.K.flavor==="playready"&&b.L("html5_innertube_heartbeats_for_playready");var c=b.K.flavor==="widevine"&&b.L("html5_innertube_heartbeats_for_widevine");b=g.LQ(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},xxb=function(a){if(wxb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.LS(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Pl&&!b.HD?!1:!!b.heartbeatToken},C6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(xxb(a)||c.isLivePlayback){if(b===void 0)if(a.G)if(a.D)b=7500;else{var d;b=((d=a.heartbeatParams)==null?0:d.interval)?a.heartbeatParams.interval*1E3:a.getVideoData().Z2||6E4}else b=1E3;a.B.start(b)}}},Bxb=function(a,b,c){b.pp&&(c=g.yo(c,{internalipoverride:b.pp}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Kb&&(d.kpt=b.Kb);c=g.yo(c,d);g.yA(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&D6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=yxb(e);if(f){a.player.ib("onHeartbeat",f);var h=f.status==="ok"?f.stop_heartbeat?2:0:f.status==="stop"?1:f.status==="live_stream_offline"?0:-1}else h=(h=e.match(zxb))?h[1]==="0"?0:1:-1;Axb(a,void 0,f,e,h)}},
onError:function(e){D6(a)&&E6(a,!0,"net-"+e.status)},
onTimeout:function(){D6(a)&&E6(a,!0,"timeout")},
withCredentials:!0})},oxb=function(a){var b,c;
g.G(function(d){b=a.player.U();c=a.getVideoData();if(!D6(a))return d.return();if(wxb(a))return Cxb(a,b,c),d.Ia(0);pxb(a);return g.z(d,Dxb(a,b,c),0)})},Cxb=function(a,b,c){var d;
if((d=a.heartbeatParams)!=null&&d.url){var e=g.yo(a.heartbeatParams.url,{request_id:g.Lva()});c.Ca&&(e=g.yo(e,{vvt:c.Ca}),c.mdxEnvironment&&(e=g.yo(e,{mdx_environment:c.mdxEnvironment})));g.IR(b,c.oauthToken).then(function(f){f&&(e=g.yo(e,{access_token:f}));Bxb(a,c,e)})}},D6=function(a){var b=a.getVideoData();
return a.player.getPresentingPlayerType()===3||g.pF(a.player.getPlayerStateObject(a.getPlayerType()),4)?!1:xxb(a)||b.isLivePlayback?!0:(F6(a),!1)},Dxb=function(a,b,c){var d,e,f,h,l,m,n,p,q,r,t,u,w,A,C,F,H,M,N,Q;
return g.G(function(da){if(da.j==1)return d="player/heartbeat",f={videoId:c.videoId,sequenceNumber:a.sequenceNumber,heartbeatServerData:(e=a.ra)!=null?e:c.heartbeatServerData},a.Y=a.attestationResponse,c.Tl?g.z(da,a.Y,3):da.Ia(2);da.j!=2&&(f.attestationResponse=da.B);h=g.hT(c);m=(l=h.client)!=null?l:{};m.utcOffsetMinutes=a.utcOffsetMinutes;f.context=h;f.cpn=c.clientPlaybackNonce;if(n=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=n;p={heartbeatChecks:[]};
if(q=c.getPlayerResponse())c.heartbeatToken&&(f.heartbeatToken=c.heartbeatToken),(r=q.playabilityStatus)&&(t=r.liveStreamability)&&t.liveStreamabilityRenderer&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.oI(b)&&(p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),u=Exb(a),w={},u!==null&&(w.clientPlayerPositionUtcMillis=u),C=(A=a.player.zb())==null?void 0:g.AV(A),H=((F=C)==null?void 0:F.freePreviewWatchedDuration)||
0,H>0&&(w.freePreviewWatchedDuration={seconds:""+H}),p.unpluggedParams=w);f.heartbeatRequestParams=p;c.isLivePlayback?(M=Exb(a),M!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={utcTimeMillis:M})):b.L("enable_heartbeat_vod_playback_position")&&(N=Fxb(a),N!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={streamTimeMillis:N}));a.player.publish("heartbeatRequest",f);Q={timeout:3E4,onSuccess:function(na){if(!a.B.isActive()&&D6(a)){var qa=
a.getVideoData(),ha=qa.Tl&&a.Y==null,ta;qa.Tl=!((ta=na.heartbeatAttestationConfig)==null||!ta.requiresAttestation)||ha;ha=na.playabilityStatus;ta=JSON.stringify(ha)||"{}";na.authenticationMismatch&&a.player.ma("authshear",{});var P=-1;var ua=na.playabilityStatus;ua&&(a.player.ib("onHeartbeat",ua),ua.status==="OK"?P=na.stopHeartbeat?2:0:ua.status==="UNPLAYABLE"?P=1:ua.status==="LIVE_STREAM_OFFLINE"&&(P=0));a.sequenceNumber&&P===-1||a.K.reset();a.sequenceNumber++;na.heartbeatServerData&&(a.ra=na.heartbeatServerData);
qa.JD=na;(ua=na.playerCueRangeSet)&&g.pXa(qa,ua);na.playerCueRanges&&na.playerCueRanges.length>0&&(qa.cueRanges=na.playerCueRanges);var y,Z;((y=na.progressBarConfig)==null?0:y.progressBarStartPosition)&&((Z=na.progressBarConfig)==null?0:Z.progressBarEndPosition)&&(qa.progressBarStartPosition=na.progressBarConfig.progressBarStartPosition,qa.progressBarEndPosition=na.progressBarConfig.progressBarEndPosition);qa.compositeLiveIngestionOffsetToken=na.compositeLiveIngestionOffsetToken;na.compositeLiveStatusToken!==
qa.compositeLiveStatusToken&&(qa.compositeLiveStatusToken=na.compositeLiveStatusToken);qa.publish("dataupdated");Axb(a,na,ha,ta,P)}},
onError:function(na){D6(a)&&E6(a,!0,"net-"+na.status)},
onTimeout:function(){D6(a)&&E6(a,!0,"timeout")}};
g.IR(b,g.bT(c)).then(function(na){na&&(Q.PW="Bearer "+na);g.cD(a.qa,d,f,Q)});
g.Aa(da)})},Axb=function(a,b,c,d,e){e===-1?(c="decode "+g.Cg(d,3),E6(a,!1,c)):e===2?(F6(a),a.G=!0):(a.Z=0,a.B.stop(),e===1?(a.G=!1,c&&c.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&a.player.Ro(!0),e="pe."+(c==null?void 0:c.errorCode)+";ps."+(c==null?void 0:c.status),a.player.Of("heartbeat.stop",2,a.xf(d),e),g.MB("heartbeatActionPlayerHalted",Gxb(c)),(b==null?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.V(b,g.AS))&&Hxb(a,d,c,{itct:b==null?void 0:b.clickTrackingParams}))):(a.G=
!0,d=0,a.D&&c&&(d=rxb(a,b,c),a.player.publish("livestatedata",c)),d?C6(a,d):C6(a)))},rxb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&d.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
b=Ixb(a,b,d);var f=a.getVideoData(),h=a.player.getPlayerStateObject(a.getPlayerType()),l=h.isPlaying()&&!g.RS(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().yc()){var m,n=((m=a.player.Le())==null?void 0:m.uc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.ma("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.V(d.streamTransitionEndpoint,g.AS);if((d&&d.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&Hxb(a,e,c))return b;if(c.status.toUpperCase()==="OK"){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&e!=null;if(!g.OS(f)||l){var p={video_id:f.videoId};f.QD&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.Bn;p.Sm=f.Sm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.un);f.Ca&&(p.vvt=f.Ca);d=void 0;g.OS(f)?l&&(d=new B6("broadcastIdChanged",m+","+e),a.AK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new B6("formatsReceived",""+e)),a.AK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Fg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Ib&&a.api.lC()):h.isBuffering()&&(f=((p=a.player.Le())==null?void 0:p.uc())||{},a.player.ma("hbse",f,!0),a.player.lC(),a.player.ib("onLiveMediaEnded",c)));return b},Ixb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(b==null?void 0:b.pollDelayMs))?a:(c=Number(c==null?void 0:c.pollDelayMs))?c:0},E6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.I3||b&&!g.LS(a.getVideoData())&&!xxb(a)&&f.isLivePlayback)f=!1;else{var h,l;((l=a.heartbeatParams)==null?0:l.retries)?h=a.heartbeatParams.retries:h=f.F3||5;f=a.Z>=h}f?(g.MB("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Gxb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Of(e,1,"Video playback interrupted. Please try again.",c):a.player.Of(e,1,"Sorry, there was an error licensing this video.",
c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Is(e,{msg:c}),C6(a,a.K.getValue()),g.Xm(a.K))}},Gxb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},F6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},qxb=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.ZUa(c.G)){a.D=!0;a.N=!0;if(!g.qI(c)||g.oI(c))a.offlineSlate=new mxb(a.player),g.L(a,a.offlineSlate),g.ET(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;((d=a.j)==null?void 0:d.status)!=="UNPLAYABLE"&&(a.j?(d=Ixb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?C6(a,d):C6(a,7500):C6(a,1E3))}else a.player.Of("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Eb(b.La,"heartbeat")&&a.player.Fg("heartbeat",a.getPlayerType())},Hxb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.jp(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.bT(a.getVideoData())),a.AK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},Exb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(a*1E3):null},Fxb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(a*1E3):null},yxb=function(a){try{var b=JSON.parse(a);
return b!=null?b:void 0}catch(c){}},Jxb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},Kxb=Jxb;Kxb=Jxb;var vxb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=dxb.prototype;g.k.WX=Kxb.FIRSTDAYOFWEEK;g.k.XX=Kxb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new dxb(this.date);a.WX=this.WX;a.XX=this.XX;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+a.years*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);a:{switch(b){case 1:var d=c%4!=0||c%100==0&&c%400!=0?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=c>=0&&c<=99?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+a.days*864E5),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),x6(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=a<0?"-":a>=1E4?"+":"";return[b+$wb(Math.abs(a),b?6:4),$wb(this.getMonth()+1,2),$wb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Lxb=new g.Gw("addUpcomingEventReminderEndpoint");var Mxb=new g.Gw("removeUpcomingEventReminderEndpoint");var Nxb=new g.Gw("updateUpcomingEventReminderButtonStateCommand");var fxb=new g.Gw("upcomingEventReminderButtonRenderer"),lxb=new g.Gw("upcomingEventReminderButtonStateRenderer");g.x(y6,g.IT);
y6.prototype.updateMenuItems=function(){var a=this,b=exb(this),c=0;c=0;for(var d={};c<b.length;d={lZ:void 0},c++){var e=this.C[c];e||(e=new g.W({I:"div",S:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",va:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",va:"{{text}}"}]}),d.lZ=c,e.listen("click",function(h){return function(){var l=h.lZ;a.Nb();l=exb(a)[l];a.publish("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ja(this.items),
this.C[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=axb();break;case "NOTIFICATIONS_NONE":d=bxb();break;case "NOTIFICATIONS_ACTIVE":d=g.Mya()}f=f.text?g.IE(f.text):"";e.update({icon:d,text:f})}for(;c<this.C.length;)this.C.pop().dispose();c===0?this.Nb():this.yd(this.j)};
y6.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.IT.prototype.hide.call(this)};
y6.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.IT.prototype.show.call(this)};
y6.prototype.xa=function(){g.vb(this.C);g.IT.prototype.xa.call(this)};g.x(z6,g.W);
z6.prototype.K=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;A6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Ib)this.j.Nb();else{var b=ixb(this);b&&this.C(b.serviceEndpoint||b.command);b=((a=g.V(b==null?void 0:b.command,g.tF))==null?void 0:a.commands)||[];a:{a=g.v(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=(b=g.V(c.value,g.dnb))==
null?void 0:(d=b.popup)==null?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new y6(this.J,this.G),this.j.Ja(this.element),g.L(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;b.updateMenuItems()}};
z6.prototype.C=function(a){var b=g.V(a,Lxb),c=g.V(a,Mxb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(kxb(this,e,d.params),a=g.v(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.V(b,Nxb)){this.B=g.V(b,Nxb).state;A6(this);break}}};g.x(mxb,g.W);g.k=mxb.prototype;g.k.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ta=function(a){var b,c,d=a==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.l3():nxb(this,b);var e,f,h,l;if(c=a==null?void 0:(e=a.liveStreamability)==null?void 0:(f=e.liveStreamabilityRenderer)==null?void 0:(h=f.offlineSlate)==null?void 0:(l=h.liveStreamOfflineSlateRenderer)==null?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new z6(this.api),this.j.Ja(this.Ea("ytp-offline-slate-buttons")),g.L(this,this.j)),gxb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&gxb(this.j,null,null);this.B=a}else this.B=null;this.q3()};
g.k.q3=function(a){if(this.api.getPresentingPlayerType()===8)var b=!0;else{var c=this.api.getPlayerStateObject(),d=this.getVideoData();b=d.isLivePlayback&&(c.isBuffering()||g.pF(c,2)||g.pF(c,64));var e=d.autonavState===2&&g.pF(c,2);c=c.isPlaying()&&!g.RS(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Ib?(a==null?0:g.rF(a,2))&&!this.getVideoData().jm&&(g.Dv(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.Dv(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.D.start(),this.api.publish("offlineslatestatechange"),this.K&&this.api.lC()):this.Ib&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.l3=function(){var a,b,c,d,e=(a=this.B)==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:(d=c.offlineSlate)==null?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.kb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(nxb(this,e),this.countdownTimer.stop()):(nxb(this,e,g.zF(b-a)),g.vv(this.countdownTimer)))};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.xa.call(this)};B6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
B6.prototype.isExpired=function(){return(0,g.$B)()-this.C>6E4};
B6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.x(txb,g.dV);g.k=txb.prototype;g.k.xa=function(){F6(this);this.player.tf("heartbeat");g.dV.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;C6(this,2E3)};
g.k.jG=function(a){this.heartbeatParams=a;C6(this,2E3)};
g.k.u5=function(a){var b;this.player.getPresentingPlayerType()!==8&&((b=this.j)==null?void 0:b.status)!=="UNPLAYABLE"&&(g.pF(a.state,2)||g.pF(a.state,64)?(F6(this),this.D&&(this.N=!0,C6(this,1E3))):(g.pF(a.state,1)||g.pF(a.state,8))&&C6(this,2E3))};
g.k.v5=function(){this.player.getPresentingPlayerType()!==3&&C6(this,2E3)};
g.k.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.fn=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.AK=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.MB("heartbeatActionPlayerTransitioned",a)};
g.k.xf=function(a){var b="LICENSE",c=yxb(a);if(c)return c.reason||g.JV[b]||"";(a=a.match(zxb))&&(a=Number(a[1]))&&(b=g.TEa(a));return g.JV[b]||""};
g.k.vF=function(){return!!this.offlineSlate&&this.offlineSlate.Ib};
var zxb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.cV("heartbeat",txb);})(_yt_player);
