name: 3 - Test Django Basic

on:
  workflow_dispatch:
  push:
    branch:
      - dev
      - main

jobs:
  test:
    env:
      DJANGO_DEBUG = 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Create a secret key
        run:
          MY_GEN_KEY = $(opnessl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >>$GITHUB_ENV
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test